apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: eduazureregistryhgy.azurecr.io
    newTag: main-20240809071751

commonLabels:
  app: frontend-vue
  environment: dev
