apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: eduazureregistryhgy.azurecr.io
    newTag: main-20240809051725

commonLabels:
  app: backend-java
  environment: dev
